---
spack_home: "/grand/VeloC/runderwood/spack/{{inventory_hostname}}"
setup_spack_build_env: |
  if hostname | grep thetagpu &>/dev/null; then
        echo "loading thetagpu spack"
       source /projects/VeloC/runderwood/spack/thetagpu/share/spack/setup-env.sh
       export clustername=thetagpu
    elif hostname -f | grep polaris &>/dev/null; then
       echo "loading polaris spack"
       source /lus/grand/projects/VeloC/runderwood/spack/polaris/share/spack/setup-env.sh
       module reset
       module load craype-accel-nvidia80
       module swap PrgEnv-nvhpc PrgEnv-gnu
       module use /soft/modulefiles
       module load cudatoolkit-standalone/12.5.2
       export clustername=polaris
    fi
    export SPACK_USER_CONFIG_PATH="$HOME/.spack/$clustername"
    export SPACK_USER_CACHE_PATH="$SPACK_USER_CONFIG_PATH"
site_settings: |
  export HTTP_PROXY="http://proxy-01.pub.alcf.anl.gov:3128"
  export HTTPS_PROXY="http://proxy-01.pub.alcf.anl.gov:3128"
  export http_proxy="http://proxy-01.pub.alcf.anl.gov:3128"
  export https_proxy="http://proxy-01.pub.alcf.anl.gov:3128"
  export ftp_proxy="http://proxy-01.pub.alcf.anl.gov:3128"
  export no_proxy="admin,polaris-adminvm-01,localhost,*.cm.polaris.alcf.anl.gov,polaris-*,*.polaris.alcf.anl.gov,*.alcf.anl.gov"
  if hostname -f | grep polaris &>/dev/null; then
     module reset
     module load craype-accel-nvidia80
     module swap PrgEnv-nvhpc PrgEnv-gnu
     module use /soft/modulefiles
     module load cudatoolkit-standalone/12.5.0
     export clustername=polaris
  fi
hf_home: "/lus/eagle/projects/LLM4CS/runderwood"
