---
- block:
  - name: add 3rd party repos
    ansible.builtin.get_url:
      url: "{{item.url}}"
      dest: "{{item.dest}}"
    with_items:
      - url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      - url: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        dest: /etc/yum.repos.d/tailscale.repo
      - url: https://cli.github.com/packages/rpm/gh-cli.repo
        dest: /etc/yum.repos.d/gh-cli.repo
    become: yes
    tags:
      - developer
      - developer_repos
  - name: install 3rd party copr repos
    community.general.copr:
      name: scottames/ghostty
      state: enabled
    become: yes
    tags:
      - developer
      - developer_repos
  when: ansible_facts['os_family'] == 'RedHat'
- block:
    - name: check if XCode Command Line tools are installed
      command: xcode-select -p
      register: xcode_select
      ignore_errors: yes
      changed_when: false
      tags:
        - developer
    - name: Install Xcode Command Line Tools
      command: xcode-select --install
      when: xcode_select.rc != 0
      tags:
        - developer
  when: ansible_facts['os_family'] == 'Darwin'
- name: install developer tools
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  with_items: "{{ packages[ansible_facts['os_family']] | default([])}}"
  become: "{{ansible_facts['os_family'] != 'Darwin'}}"
  tags:
    - developer
    - developer_tools
- name: enable developer services
  ansible.builtin.service:
    name: "{{item}}"
    state: started
    enabled: yes
  with_items: "{{ services[ansible_facts['os_family']] | default([])}}"
  become: yes
  tags:
    - developer
    - developer_services
- name: configure firewall for tailscale
  ansible.posix.firewalld: # does this need to be done differently?
    zone: trusted
    interface: tailscale0
    state: enabled
    permanent: true
  become: yes
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - developer
    - developer_services

