#!/bin/bash
hsetroot -fill $HOME/Pictures/Backgrounds/$(ls $HOME/Pictures/Backgrounds/ | sort -R | head -n 1)
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
eval $(/usr/bin/ssh-agent -s)

urxvt &
panel &
