# Appearance Options
set -g default-terminal "screen-256color"
set -g base-index 1
set -g pane-base-index 1
setw -g aggressive-resize on
set-window-option -g monitor-activity on
set-option -g status-justify left
set-option -g status-bg black
set-option -g status-fg cyan
set-option -g status-interval 5
set-option -g status-left-length 30
set-option -g status-left '#[fg=magenta]» #[fg=blue,bold]#T#[default]'
set-option -g status-right '#[fg=magenta,bold]%R %m-%d'
set-option -g visual-activity on


set-option -g set-titles on
set-option -g set-titles-string '#H'

# History Options
set -g history-limit 10000

# Key Bindings
set-window-option -g status-keys vi
set-window-option -g mode-keys vi
bind-key -t vi-copy v begin-selection
{% if ((grains['tmux_major_version']|int == 2 and grains['tmux_minor_version']|int >= 1) or grains['tmux_major_version']|int > 2) %}
	set -g mouse on
{% else %}
	set-option -g mouse-select-pane on
{% endif %}

bind ^a send-prefix

## Create splits and windows
bind s split-window -v
bind v split-window -h
bind e new-window
bind w list-window
bind @ choose-session
bind \ source-file ~/.tmux.conf


## Move between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

## Move between windows
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

## Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

## Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-logging'

## Plugin Settings
set -g @resurrect-strategy-vim 'session'
set -g @shell_mode 'vi'

run ~/.tmux/plugins/tpm/tpm
