---
- name: check should install {{name}}
  shell: 'which {{name}}'
  register: cmd
  ignore_errors: yes
  changed_when: no
- name: 'download {{name}}'
  get_url: 
    url: '{{src}}'
    dest: '{{ansible_user_dir}}/.local/cache/{{name}}.sh'
    mode: 0744
  when: cmd.rc != 0
- name: 'install {{name}}'
  shell: '{{ansible_user_dir}}/.local/cache/{{name}}.sh {{extra_args}}'
  when: cmd.rc != 0
