---
- name: setup prefered directory sturcture
  file:
    path: '{{item}}'
    state: directory
    mode: 0755
  loop:
    - "{{ ansible_facts['user_dir'] }}/.config"
    - "{{ ansible_facts['user_dir'] }}/.config/git"
    - "{{ ansible_facts['user_dir'] }}/.config/nvim"
    - "{{ ansible_facts['user_dir'] }}/.local"
    - "{{ ansible_facts['user_dir'] }}/.ssh/control_channels"
    - "{{ ansible_facts['user_dir'] }}/.local/bin"
    - "{{ ansible_facts['user_dir'] }}/.local/cache"
    - "{{ ansible_facts['user_dir'] }}/git"
    - "{{ ansible_facts['user_dir'] }}/git/contrib"
    - "{{ ansible_facts['user_dir'] }}/git/datasets"
  tags:
    - nvim
    - mamba
    - shell
    - shellcmd
    - shellconfig
    - dotfiles
- name: setup various dotfiles
  template:
    src: '{{item.src}}'
    dest: '{{item.dst}}'
    mode: 0644
  loop:
    - { src: 'init.lua.j2',    dst: "{{ ansible_facts['user_dir'] }}/.config/nvim/init.lua" }
    - { src: 'gitconfig.j2',   dst: "{{ ansible_facts['user_dir'] }}/.gitconfig" }
    - { src: 'gitexcludes.j2', dst: "{{ ansible_facts['user_dir'] }}/.config/git/ignore" }
    - { src: 'gdb.j2',         dst: "{{ ansible_facts['user_dir'] }}/.gdbinit" }
    - { src: 'sshconfig.j2',   dst: "{{ ansible_facts['user_dir'] }}/.ssh/config" }
    - { src: 'bashrc.j2',      dst: "{{ ansible_facts['user_dir'] }}/.bashrc" }
    - { src: 'bashrc.j2',      dst: "{{ ansible_facts['user_dir'] }}/.zshrc" }
  tags:
    - uv
    - nvim
    - shell
    - shellcmd
    - shellconfig
    - dotfiles
- name: install dotfiles packages
  include_tasks: "roles/dotfiles/tasks/install_{{ ansible_facts['os_family'] | lower }}.yaml"
  tags:
    - dotfiles
- name: 'check if cargo installed'
  shell: 'which cargo'
  ignore_errors: true
  register: cargo_installed
  changed_when: false
  tags:
    - rust
    - dotfiles
- name: install rust based commands
  include_tasks: cargo_install.yaml
  vars:
    pkg_name: '{{item.pkg_name}}'
    pkg: '{{item.pkg}}'
  loop:
    - { pkg_name: 'mpigdb', pkg: 'mpigdb' }
  when: cargo_installed.rc == 0
  tags:
    - rust
    - shellcmd
    - dotfiles
- name: check pip installed
  shell: 'which pip3'
  ignore_errors: yes
  register: pip_installed
  changed_when: false
  tags:
    - shellcmd
    - dotfiles
- name: install m
  pip:
    name: git+http://github.com/robertu94/m
    extra_args: '--user'
  when: pip_installed.rc == 0
  tags:
    - shellcmd
    - dotfiles
- name: download spack
  git:
    repo: 'https://github.com/spack/spack'
    dest: '{{spack_home}}'
    update: no
  when: pip_installed.rc == 0
  tags:
    - shellcmd
    - spack
    - dotfiles
